### ISSUE TITLE
Academic Papers Section

### ISSUE THREAD

**Issue by brandonbryan12** [aisutd/aisutd.github.io#9]
Give a small summary of each paper in a non-rigorous fashion. This can go from Alan Turing's inaugural paper on Artificial Intelligence, to Andrew Ng’s famous modern paper on Latent Dirichlet Allocation.

**Comment by brandonbryan12** [comment]
Each item should have the following: {Title, link, release date, author, category (machine learning, computer vision, etc.), summary}

Possible implementations:

- List similar to Team page
- Vertical list
- If there are many submissions, a search function may be leveraged

Any other ideas?

**Comment by Michael-Hollister** [comment]
Unless we want an unconventional design, a vertical list seems promising for listing the items. It also may be easier to implement than the grid system used on the team page.

As for content filtering and searching, a header or sidebar (may be an issue for mobile devices) might suffice when we write enough entries.

Additional non-essential features that we could consider in the future are listing the post author (the person who writes the summary) and adding a comments section. If I recall correctly, our website base theme (Minimal Mistakes) already supports this functionality.

**Comment by WillieCubed** [comment]
Ha, this should have been closed years ago. I'd like to do something similar now, but that will have to wait until after the site redesign.
